[build-system]
requires = ["setuptools>=50.0"]
build-backend = "setuptools.build_meta"

[project]
name = "myna"
version = "0.1.0.dev0"
authors = [
    { name="Gerry Knapp", email="knappgl@ornl.gov" },
    { name="Sam Reeve", email="reevest@ornl.gov"},
    { name="John Coleman", email="colemanjs@ornl.gov"},
    { name="Jamie Stump", email="stumpbc@ornl.gov"},
    { name="Stephen DeWitt", email="dewittsj@ornl.gov"}]
description = "A structured interface between Additive Manufacturing build database(s) and multi-stage modeling and simulation workflows"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"]
dependencies = [
    'PyYAML',
    'numpy',
    'pandas',
    'matplotlib',
    'mistlib @ git+https://github.com/ORNL-MDF/mist.git',
    'vtk',
    'h5py',
    'polars',
    'bnpy @ git+https://github.com/gknapp1/bnpy',
    'pyebsd @ git+https://github.com/arthursn/pyebsd.git',]

[project.optional-dependencies]
dev = [
  'pytest',
  'black']

[project.scripts]
myna_run = "myna.core.workflow.run:main"
myna_config = "myna.core.workflow.config:main"
myna_sync = "myna.core.workflow.sync:main"
myna_status = "myna.utils.codebase_status:write_codebase_status_to_file"
myna_peregrine_launcher = "myna.core.workflow.launch_from_peregrine:launch_from_peregrine"

[tool.setuptools]
py-modules = ["myna"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib"]

[tool.codespell]
ignore-words-list = 'mater,nd'
skip = './resources'
quiet-level = 3
