---
Peregrine:
  build_path: "/home/cloud/myna/resources/Peregrine"
  build_name: "myna_test"

3DThesis:
    root: "/home/cloud"
    repo: "/home/cloud/3DThesis"
    executable: "/home/cloud/3DThesis/3DThesis"
    input_dir_path: "/home/cloud/myna/resources/3DThesis/template"
    input_file_path: "/home/cloud/myna/resources/3DThesis/template/ParamInput.txt"
    material_database_path: "/home/cloud/myna/resources/3DThesis/materials"
    output_dir_path: "/home/cloud/myna/examples/demo/results/3DThesis"
    parts:
      - part_number: 6
        layer_start: 50
        layer_end: 50
    Peregrine:
        upload: true
        variables:
          - varname: "G"
            exportname: "Gradient"
            unit: "K/m"
          - varname: "V"
            exportname: "Velocity"
            unit: "m/s"

classification:
    output_dir_path: "/home/cloud/myna/examples/demo/results/classification"

rve:
  output_dir_path: "/home/cloud/myna/examples/demo/results/rve"

autofoam:
    mesh:
      stl_path: "/home/cloud/myna/resources/autofoam/stl_library/zeiss_part.stl"
      convertToMeters: 0.001
      spacing: [200.0e-6, 200.0e-6, 200.0e-6]
      refinement: 0
      tolerance: 1.0e-08
    template:
      template_dir: "/home/cloud/myna/resources/autofoam/template"
    case_dir: "results"
    rve_size: [1.0e-3, 1.0e-3, 0.5e-3]
    exe:
      nProcs: 8
      mpiArgs: "mpirun -n 8"

exaca:
  template:
    path: "/home/cloud/myna/resources/exaca/template"
    input_file: "inputs.json"
    material_file: "SS316.json"
    orientation_file: "GrainOrientationVectors.csv"
  case_dir: "/home/cloud/myna/examples/demo/results"
  additivefoam_export_name: "solidificationData.csv"
  case_path_var: "MYNA_SIM_PATH"
  exaca_path_var: "EXACA_EXE_PATH"
       
  inputs:
    - variable: ["Nucleation", "Density"]
      value: 1000
      file: "inputs.json"
    - variable: ["Nucleation", "StDev"]
      value: 2
      file: "inputs.json"
      dependents:
        - variable: ["Nucleation", "MeanUndercooling"]
          scale: 3.0
          file: "inputs.json"
...